### PR TITLE
Make a subset of gadget-sdk no_std compatible

### PR DESCRIPTION
**Pull request by Serial-ATA**
Each commit message speaks for itself, the only major change is the addition of `GadgetEnvironment::load_with_lock<R>()` where `R` is `lock_api::RawRwLock`. This allows callers to bring their own lock in `no_std` environments. `GadgetEnvironment::load()` is now `std` only, and will use `parking_lot::RawRwLock` as before.

### CODE REVIEW

**Comment by drewstone** [comment]
Looks like CI wants improvements to the docs @Serial-ATA

**Comment by Serial-ATA** [comment]
Fixed, I forgot to check Clippy after making those modules public.

**Comment by drewstone** [comment]
Might need to update to latest Tangle deps to get the spelling error fix. I'm double-checking its in now.

**Review by drewstone — COMMENTED** [review]
We should aim to get rid of the `wasm` feature and `getrandom`.

**Review by drewstone — APPROVED** [review]

**Pull request merged**
